import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
function timestamp(){const d=new Date();const parts=[d.getUTCFullYear(),String(d.getUTCMonth()+1).padStart(2,"0"),String(d.getUTCDate()).padStart(2,"0"),String(d.getUTCHours()).padStart(2,"0"),String(d.getUTCMinutes()).padStart(2,"0"),String(d.getUTCSeconds()).padStart(2,"0")];return parts.join("");}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const key=Deno.env.get("MPESA_CONSUMER_KEY"),secret=Deno.env.get("MPESA_CONSUMER_SECRET"),shortcode=Deno.env.get("MPESA_SHORTCODE"),passkey=Deno.env.get("MPESA_PASSKEY"),callback=Deno.env.get("MPESA_CALLBACK_URL"),env=Deno.env.get("MPESA_ENV")||"sandbox";
 if(!url||!anon||!service||!key||!secret||!shortcode||!passkey||!callback)return json({error:"M-Pesa is not configured. Add MPESA_CONSUMER_KEY, MPESA_CONSUMER_SECRET, MPESA_SHORTCODE, MPESA_PASSKEY and MPESA_CALLBACK_URL as Edge Function secrets."},503);
 const auth=req.headers.get("Authorization");if(!auth)return json({error:"Missing authorization"},401);const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:ue}=await userClient.auth.getUser();if(ue||!user)return json({error:"Unauthenticated"},401);
 let body:any;try{body=await req.json()}catch{return json({error:"Invalid JSON"},400)}const studentId=String(body.studentId||""),amount=Number(body.amount||0),phone=String(body.phone||"").trim();if(!studentId||amount<=0||!phone)return json({error:"studentId, amount and phone are required"},400);
 const admin=createClient(url,service);const {data:link}=await admin.from("parent_student").select("student_id").eq("parent_id",user.id).eq("student_id",studentId).maybeSingle();if(!link)return json({error:"You can only pay for your linked child."},403);
 const {data:tx,error:te}=await admin.from("mpesa_transactions").insert({student_id:studentId,parent_id:user.id,amount,phone,account_reference:`RAHMA-${studentId.slice(0,8)}`}).select("id,account_reference").single();if(te)return json({error:te.message},500);
 const base=env==="production"?"https://api.safaricom.co.ke":"https://sandbox.safaricom.co.ke";const basic=btoa(`${key}:${secret}`);const tokenRes=await fetch(`${base}/oauth/v1/generate?grant_type=client_credentials`,{headers:{Authorization:`Basic ${basic}`}});const tokenData=await tokenRes.json();if(!tokenRes.ok)return json({error:"Could not authenticate with M-Pesa",details:tokenData},502);
 const ts=timestamp();const password=btoa(`${shortcode}${passkey}${ts}`);const normalized=phone.replace(/^\+254/,"254").replace(/^0/,"254");const stk=await fetch(`${base}/mpesa/stkpush/v1/processrequest`,{method:"POST",headers:{Authorization:`Bearer ${tokenData.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({BusinessShortCode:shortcode,Password:password,Timestamp:ts,TransactionType:"CustomerPayBillOnline",Amount:Math.round(amount),PartyA:normalized,PartyB:shortcode,PhoneNumber:normalized,CallBackURL:callback,AccountReference:tx.account_reference,TransactionDesc:"Rahma school fees"})});const data=await stk.json();if(!stk.ok||data.ResponseCode!=="0"){await admin.from("mpesa_transactions").update({status:"failed",result_description:data.ResponseDescription||"M-Pesa rejected request"}).eq("id",tx.id);return json({error:data.ResponseDescription||"M-Pesa request failed",details:data},502);}await admin.from("mpesa_transactions").update({checkout_request_id:data.CheckoutRequestID,merchant_request_id:data.MerchantRequestID}).eq("id",tx.id);return json({success:true,message:data.CustomerMessage||"STK push sent",checkoutRequestId:data.CheckoutRequestID});
});
