/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPortalAdmissionsRouteImport } from './routes/_authenticated/portal.admissions'
import { Route as AuthenticatedPortalAnnouncementsRouteImport } from './routes/_authenticated/portal.announcements'
import { Route as AuthenticatedPortalAttendanceRouteImport } from './routes/_authenticated/portal.attendance'
import { Route as AuthenticatedPortalClassesRouteImport } from './routes/_authenticated/portal.classes'
import { Route as AuthenticatedPortalExamsRouteImport } from './routes/_authenticated/portal.exams'
import { Route as AuthenticatedPortalFinanceRouteImport } from './routes/_authenticated/portal.finance'
import { Route as AuthenticatedPortalInventoryRouteImport } from './routes/_authenticated/portal.inventory'
import { Route as AuthenticatedPortalMessagesRouteImport } from './routes/_authenticated/portal.messages'
import { Route as AuthenticatedPortalParentsRouteImport } from './routes/_authenticated/portal.parents'
import { Route as AuthenticatedPortalParentsParentIdRouteImport } from './routes/_authenticated/portal.parents.$parentId'
import { Route as AuthenticatedPortalPeopleRouteImport } from './routes/_authenticated/portal.people'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPortalStaffRouteImport } from './routes/_authenticated/portal.staff'
import { Route as AuthenticatedPortalStudentsRouteImport } from './routes/_authenticated/portal.students'
import { Route as AuthenticatedPortalTimetableRouteImport } from './routes/_authenticated/portal.timetable'
import { Route as AuthenticatedPortalStudentsStudentIdRouteImport } from './routes/_authenticated/portal.students.$studentId'
import { Route as AuthenticatedPortalAcademicRouteImport } from './routes/_authenticated/portal.academic'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal.documents'
import { Route as AuthenticatedPortalCalendarRouteImport } from './routes/_authenticated/portal.calendar'
import { Route as AuthenticatedPortalAuditLogsRouteImport } from './routes/_authenticated/portal.audit-logs'
import { Route as AuthenticatedPortalReportsRouteImport } from './routes/_authenticated/portal.reports'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalAdmissionsRoute =
  AuthenticatedPortalAdmissionsRouteImport.update({
    id: '/portal/admissions',
    path: '/portal/admissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAnnouncementsRoute =
  AuthenticatedPortalAnnouncementsRouteImport.update({
    id: '/portal/announcements',
    path: '/portal/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAttendanceRoute =
  AuthenticatedPortalAttendanceRouteImport.update({
    id: '/portal/attendance',
    path: '/portal/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalClassesRoute =
  AuthenticatedPortalClassesRouteImport.update({
    id: '/portal/classes',
    path: '/portal/classes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalExamsRoute =
  AuthenticatedPortalExamsRouteImport.update({
    id: '/portal/exams',
    path: '/portal/exams',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalFinanceRoute =
  AuthenticatedPortalFinanceRouteImport.update({
    id: '/portal/finance',
    path: '/portal/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalInventoryRoute =
  AuthenticatedPortalInventoryRouteImport.update({
    id: '/portal/inventory',
    path: '/portal/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalMessagesRoute =
  AuthenticatedPortalMessagesRouteImport.update({
    id: '/portal/messages',
    path: '/portal/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalParentsRoute =
  AuthenticatedPortalParentsRouteImport.update({
    id: '/portal/parents',
    path: '/portal/parents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalParentsParentIdRoute =
  AuthenticatedPortalParentsParentIdRouteImport.update({
    id: '/$parentId',
    path: '/$parentId',
    getParentRoute: () => AuthenticatedPortalParentsRoute,
  } as any)
const AuthenticatedPortalPeopleRoute =
  AuthenticatedPortalPeopleRouteImport.update({
    id: '/portal/people',
    path: '/portal/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/portal/profile',
    path: '/portal/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStaffRoute =
  AuthenticatedPortalStaffRouteImport.update({
    id: '/portal/staff',
    path: '/portal/staff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStudentsRoute =
  AuthenticatedPortalStudentsRouteImport.update({
    id: '/portal/students',
    path: '/portal/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalTimetableRoute =
  AuthenticatedPortalTimetableRouteImport.update({
    id: '/portal/timetable',
    path: '/portal/timetable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStudentsStudentIdRoute =
  AuthenticatedPortalStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedPortalStudentsRoute,
  } as any)
const AuthenticatedPortalAcademicRoute = AuthenticatedPortalAcademicRouteImport.update({
  id: '/_authenticated/portal/academic',
  path: '/portal/academic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalDocumentsRoute = AuthenticatedPortalDocumentsRouteImport.update({
  id: '/_authenticated/portal/documents',
  path: '/portal/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalCalendarRoute = AuthenticatedPortalCalendarRouteImport.update({
  id: '/_authenticated/portal/calendar',
  path: '/portal/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalAuditLogsRoute = AuthenticatedPortalAuditLogsRouteImport.update({
  id: '/_authenticated/portal/audit-logs',
  path: '/portal/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalReportsRoute = AuthenticatedPortalReportsRouteImport.update({
  id: '/_authenticated/portal/reports',
  path: '/portal/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalSettingsRoute = AuthenticatedPortalSettingsRouteImport.update({
  id: '/_authenticated/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal/admissions': typeof AuthenticatedPortalAdmissionsRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/classes': typeof AuthenticatedPortalClassesRoute
  '/portal/exams': typeof AuthenticatedPortalExamsRoute
  '/portal/finance': typeof AuthenticatedPortalFinanceRoute
  '/portal/inventory': typeof AuthenticatedPortalInventoryRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/parents': typeof AuthenticatedPortalParentsRoute
  '/portal/people': typeof AuthenticatedPortalPeopleRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/staff': typeof AuthenticatedPortalStaffRoute
  '/portal/students': typeof AuthenticatedPortalStudentsRouteWithChildren
  '/portal/timetable': typeof AuthenticatedPortalTimetableRoute
  '/portal/students/$studentId': typeof AuthenticatedPortalStudentsStudentIdRoute
  '/portal/academic': typeof AuthenticatedPortalAcademicRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/audit-logs': typeof AuthenticatedPortalAuditLogsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal/admissions': typeof AuthenticatedPortalAdmissionsRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/classes': typeof AuthenticatedPortalClassesRoute
  '/portal/exams': typeof AuthenticatedPortalExamsRoute
  '/portal/finance': typeof AuthenticatedPortalFinanceRoute
  '/portal/inventory': typeof AuthenticatedPortalInventoryRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/parents': typeof AuthenticatedPortalParentsRoute
  '/portal/people': typeof AuthenticatedPortalPeopleRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/staff': typeof AuthenticatedPortalStaffRoute
  '/portal/students': typeof AuthenticatedPortalStudentsRouteWithChildren
  '/portal/timetable': typeof AuthenticatedPortalTimetableRoute
  '/portal/students/$studentId': typeof AuthenticatedPortalStudentsStudentIdRoute
  '/portal/academic': typeof AuthenticatedPortalAcademicRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/audit-logs': typeof AuthenticatedPortalAuditLogsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/portal/admissions': typeof AuthenticatedPortalAdmissionsRoute
  '/_authenticated/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/_authenticated/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/_authenticated/portal/classes': typeof AuthenticatedPortalClassesRoute
  '/_authenticated/portal/exams': typeof AuthenticatedPortalExamsRoute
  '/_authenticated/portal/finance': typeof AuthenticatedPortalFinanceRoute
  '/_authenticated/portal/inventory': typeof AuthenticatedPortalInventoryRoute
  '/_authenticated/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/_authenticated/portal/parents': typeof AuthenticatedPortalParentsRoute
  '/_authenticated/portal/people': typeof AuthenticatedPortalPeopleRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/staff': typeof AuthenticatedPortalStaffRoute
  '/_authenticated/portal/students': typeof AuthenticatedPortalStudentsRouteWithChildren
  '/_authenticated/portal/timetable': typeof AuthenticatedPortalTimetableRoute
  '/_authenticated/portal/students/$studentId': typeof AuthenticatedPortalStudentsStudentIdRoute
  '/_authenticated/portal/academic': typeof AuthenticatedPortalAcademicRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/_authenticated/portal/audit-logs': typeof AuthenticatedPortalAuditLogsRoute
  '/_authenticated/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/dashboard'
    | '/portal/admissions'
    | '/portal/announcements'
    | '/portal/attendance'
    | '/portal/classes'
    | '/portal/exams'
    | '/portal/finance'
    | '/portal/inventory'
    | '/portal/messages'
    | '/portal/parents'
    | '/portal/people'
    | '/portal/profile'
    | '/portal/staff'
    | '/portal/students'
    | '/portal/timetable'
    | '/portal/students/$studentId'
    | '/portal/settings'
    | '/portal/settings'
    | '/portal/academic'
    | '/portal/documents'
    | '/portal/calendar'
    | '/portal/audit-logs'
    | '/portal/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/dashboard'
    | '/portal/admissions'
    | '/portal/announcements'
    | '/portal/attendance'
    | '/portal/classes'
    | '/portal/exams'
    | '/portal/finance'
    | '/portal/inventory'
    | '/portal/messages'
    | '/portal/parents'
    | '/portal/people'
    | '/portal/profile'
    | '/portal/staff'
    | '/portal/students'
    | '/portal/timetable'
    | '/portal/students/$studentId'
    | '/portal/academic'
    | '/portal/documents'
    | '/portal/calendar'
    | '/portal/audit-logs'
    | '/portal/reports'
    | '/portal/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/_authenticated/dashboard'
    | '/_authenticated/portal/admissions'
    | '/_authenticated/portal/announcements'
    | '/_authenticated/portal/attendance'
    | '/_authenticated/portal/classes'
    | '/_authenticated/portal/exams'
    | '/_authenticated/portal/finance'
    | '/_authenticated/portal/inventory'
    | '/_authenticated/portal/messages'
    | '/_authenticated/portal/parents'
    | '/_authenticated/portal/people'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/staff'
    | '/_authenticated/portal/students'
    | '/_authenticated/portal/timetable'
    | '/_authenticated/portal/students/$studentId'
    | '/_authenticated/portal/academic'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/calendar'
    | '/_authenticated/portal/audit-logs'
    | '/_authenticated/portal/reports'
    | '/_authenticated/portal/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/admissions': {
      id: '/_authenticated/portal/admissions'
      path: '/portal/admissions'
      fullPath: '/portal/admissions'
      preLoaderRoute: typeof AuthenticatedPortalAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/announcements': {
      id: '/_authenticated/portal/announcements'
      path: '/portal/announcements'
      fullPath: '/portal/announcements'
      preLoaderRoute: typeof AuthenticatedPortalAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/attendance': {
      id: '/_authenticated/portal/attendance'
      path: '/portal/attendance'
      fullPath: '/portal/attendance'
      preLoaderRoute: typeof AuthenticatedPortalAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/classes': {
      id: '/_authenticated/portal/classes'
      path: '/portal/classes'
      fullPath: '/portal/classes'
      preLoaderRoute: typeof AuthenticatedPortalClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/exams': {
      id: '/_authenticated/portal/exams'
      path: '/portal/exams'
      fullPath: '/portal/exams'
      preLoaderRoute: typeof AuthenticatedPortalExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/finance': {
      id: '/_authenticated/portal/finance'
      path: '/portal/finance'
      fullPath: '/portal/finance'
      preLoaderRoute: typeof AuthenticatedPortalFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/inventory': {
      id: '/_authenticated/portal/inventory'
      path: '/portal/inventory'
      fullPath: '/portal/inventory'
      preLoaderRoute: typeof AuthenticatedPortalInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/messages': {
      id: '/_authenticated/portal/messages'
      path: '/portal/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof AuthenticatedPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/parents': {
      id: '/_authenticated/portal/parents'
      path: '/portal/parents'
      fullPath: '/portal/parents'
      preLoaderRoute: typeof AuthenticatedPortalParentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/parents/$parentId': {
      id: '/_authenticated/portal/parents/$parentId'
      path: '/$parentId'
      fullPath: '/portal/parents/$parentId'
      preLoaderRoute: typeof AuthenticatedPortalParentsParentIdRouteImport
      parentRoute: typeof AuthenticatedPortalParentsRoute
    }
    '/_authenticated/portal/people': {
      id: '/_authenticated/portal/people'
      path: '/portal/people'
      fullPath: '/portal/people'
      preLoaderRoute: typeof AuthenticatedPortalPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/staff': {
      id: '/_authenticated/portal/staff'
      path: '/portal/staff'
      fullPath: '/portal/staff'
      preLoaderRoute: typeof AuthenticatedPortalStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/students': {
      id: '/_authenticated/portal/students'
      path: '/portal/students'
      fullPath: '/portal/students'
      preLoaderRoute: typeof AuthenticatedPortalStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/timetable': {
      id: '/_authenticated/portal/timetable'
      path: '/portal/timetable'
      fullPath: '/portal/timetable'
      preLoaderRoute: typeof AuthenticatedPortalTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/students/$studentId': {
      id: '/_authenticated/portal/students/$studentId'
      path: '/$studentId'
      fullPath: '/portal/students/$studentId'
      preLoaderRoute: typeof AuthenticatedPortalStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedPortalStudentsRoute
    }
    '/_authenticated/portal/academic': {
      id: '/_authenticated/portal/academic'
      path: '/portal/academic'
      fullPath: '/portal/academic'
      preLoaderRoute: typeof AuthenticatedPortalAcademicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/calendar': {
      id: '/_authenticated/portal/calendar'
      path: '/portal/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof AuthenticatedPortalCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/audit-logs': {
      id: '/_authenticated/portal/audit-logs'
      path: '/portal/audit-logs'
      fullPath: '/portal/audit-logs'
      preLoaderRoute: typeof AuthenticatedPortalAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/reports': {
      id: '/_authenticated/portal/reports'
      path: '/portal/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof AuthenticatedPortalReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPortalStudentsRouteChildren {
  AuthenticatedPortalStudentsStudentIdRoute: typeof AuthenticatedPortalStudentsStudentIdRoute
}

const AuthenticatedPortalStudentsRouteChildren: AuthenticatedPortalStudentsRouteChildren =
  {
    AuthenticatedPortalStudentsStudentIdRoute:
      AuthenticatedPortalStudentsStudentIdRoute,
  }

const AuthenticatedPortalStudentsRouteWithChildren =
  AuthenticatedPortalStudentsRoute._addFileChildren(
    AuthenticatedPortalStudentsRouteChildren,
  )

interface AuthenticatedPortalParentsRouteChildren {
  AuthenticatedPortalParentsParentIdRoute: typeof AuthenticatedPortalParentsParentIdRoute
}

const AuthenticatedPortalParentsRouteChildren: AuthenticatedPortalParentsRouteChildren = {
  AuthenticatedPortalParentsParentIdRoute: AuthenticatedPortalParentsParentIdRoute,
}

const AuthenticatedPortalParentsRouteWithChildren =
  AuthenticatedPortalParentsRoute._addFileChildren(AuthenticatedPortalParentsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPortalAdmissionsRoute: typeof AuthenticatedPortalAdmissionsRoute
  AuthenticatedPortalAnnouncementsRoute: typeof AuthenticatedPortalAnnouncementsRoute
  AuthenticatedPortalAttendanceRoute: typeof AuthenticatedPortalAttendanceRoute
  AuthenticatedPortalClassesRoute: typeof AuthenticatedPortalClassesRoute
  AuthenticatedPortalExamsRoute: typeof AuthenticatedPortalExamsRoute
  AuthenticatedPortalFinanceRoute: typeof AuthenticatedPortalFinanceRoute
  AuthenticatedPortalInventoryRoute: typeof AuthenticatedPortalInventoryRoute
  AuthenticatedPortalMessagesRoute: typeof AuthenticatedPortalMessagesRoute
  AuthenticatedPortalParentsRoute: typeof AuthenticatedPortalParentsRouteWithChildren
  AuthenticatedPortalPeopleRoute: typeof AuthenticatedPortalPeopleRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalStaffRoute: typeof AuthenticatedPortalStaffRoute
  AuthenticatedPortalStudentsRoute: typeof AuthenticatedPortalStudentsRouteWithChildren
  AuthenticatedPortalTimetableRoute: typeof AuthenticatedPortalTimetableRoute
  AuthenticatedPortalAcademicRoute: typeof AuthenticatedPortalAcademicRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalCalendarRoute: typeof AuthenticatedPortalCalendarRoute
  AuthenticatedPortalAuditLogsRoute: typeof AuthenticatedPortalAuditLogsRoute
  AuthenticatedPortalReportsRoute: typeof AuthenticatedPortalReportsRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPortalAdmissionsRoute: AuthenticatedPortalAdmissionsRoute,
  AuthenticatedPortalAnnouncementsRoute: AuthenticatedPortalAnnouncementsRoute,
  AuthenticatedPortalAttendanceRoute: AuthenticatedPortalAttendanceRoute,
  AuthenticatedPortalClassesRoute: AuthenticatedPortalClassesRoute,
  AuthenticatedPortalExamsRoute: AuthenticatedPortalExamsRoute,
  AuthenticatedPortalFinanceRoute: AuthenticatedPortalFinanceRoute,
  AuthenticatedPortalInventoryRoute: AuthenticatedPortalInventoryRoute,
  AuthenticatedPortalMessagesRoute: AuthenticatedPortalMessagesRoute,
  AuthenticatedPortalParentsRoute: AuthenticatedPortalParentsRouteWithChildren,
  AuthenticatedPortalPeopleRoute: AuthenticatedPortalPeopleRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalStaffRoute: AuthenticatedPortalStaffRoute,
  AuthenticatedPortalStudentsRoute:
    AuthenticatedPortalStudentsRouteWithChildren,
  AuthenticatedPortalTimetableRoute: AuthenticatedPortalTimetableRoute,
  AuthenticatedPortalAcademicRoute: AuthenticatedPortalAcademicRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalCalendarRoute: AuthenticatedPortalCalendarRoute,
  AuthenticatedPortalAuditLogsRoute: AuthenticatedPortalAuditLogsRoute,
  AuthenticatedPortalReportsRoute: AuthenticatedPortalReportsRoute,
  AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
