-- Rahma Edu Hub: Complete School Settings Control Center
-- Extends the existing singleton school_settings row. Safe for existing data.

ALTER TABLE public.school_settings
  ADD COLUMN IF NOT EXISTS registration_number TEXT,
  ADD COLUMN IF NOT EXISTS knec_number TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS principal_name TEXT,
  ADD COLUMN IF NOT EXISTS school_type TEXT NOT NULL DEFAULT 'private',
  ADD COLUMN IF NOT EXISTS opening_time TIME NOT NULL DEFAULT '07:30',
  ADD COLUMN IF NOT EXISTS closing_time TIME NOT NULL DEFAULT '16:30',
  ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Africa/Nairobi',
  ADD COLUMN IF NOT EXISTS date_format TEXT NOT NULL DEFAULT 'dd/MM/yyyy',
  ADD COLUMN IF NOT EXISTS time_format TEXT NOT NULL DEFAULT '24h',
  ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS academic_year TEXT NOT NULL DEFAULT '2026',
  ADD COLUMN IF NOT EXISTS current_term TEXT NOT NULL DEFAULT 'Term 1',
  ADD COLUMN IF NOT EXISTS term_start_date DATE,
  ADD COLUMN IF NOT EXISTS term_end_date DATE,
  ADD COLUMN IF NOT EXISTS pass_mark NUMERIC(5,2) NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS grading_scale TEXT NOT NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS promotion_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS parent_portal_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS student_portal_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS online_admission_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS profile_photo_required BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS teacher_subject_assignment_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS teacher_remarks_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS attendance_late_after_minutes INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS automatic_absence_alerts BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS fee_payment_sms BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS result_sms BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS birthday_notifications BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sms_sender_name TEXT,
  ADD COLUMN IF NOT EXISTS mpesa_paybill TEXT,
  ADD COLUMN IF NOT EXISTS mpesa_till TEXT,
  ADD COLUMN IF NOT EXISTS mpesa_account_name TEXT,
  ADD COLUMN IF NOT EXISTS fee_invoice_prefix TEXT NOT NULL DEFAULT 'INV',
  ADD COLUMN IF NOT EXISTS certificate_prefix TEXT NOT NULL DEFAULT 'CERT',
  ADD COLUMN IF NOT EXISTS report_card_signature_name TEXT,
  ADD COLUMN IF NOT EXISTS report_card_signature_title TEXT DEFAULT 'Head Teacher',
  ADD COLUMN IF NOT EXISTS report_card_footer TEXT,
  ADD COLUMN IF NOT EXISTS receipt_footer TEXT,
  ADD COLUMN IF NOT EXISTS primary_color TEXT NOT NULL DEFAULT '#0f766e',
  ADD COLUMN IF NOT EXISTS secondary_color TEXT NOT NULL DEFAULT '#0f172a',
  ADD COLUMN IF NOT EXISTS login_page_message TEXT,
  ADD COLUMN IF NOT EXISTS calendar_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS event_reminder_minutes INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS login_notifications BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS session_timeout_minutes INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS failed_login_protection BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS maintenance_mode BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.school_settings
  DROP CONSTRAINT IF EXISTS school_settings_pass_mark_check,
  ADD CONSTRAINT school_settings_pass_mark_check CHECK (pass_mark >= 0 AND pass_mark <= 100),
  DROP CONSTRAINT IF EXISTS school_settings_attendance_late_check,
  ADD CONSTRAINT school_settings_attendance_late_check CHECK (attendance_late_after_minutes >= 0),
  DROP CONSTRAINT IF EXISTS school_settings_timeout_check,
  ADD CONSTRAINT school_settings_timeout_check CHECK (session_timeout_minutes >= 5),
  DROP CONSTRAINT IF EXISTS school_settings_event_reminder_check,
  ADD CONSTRAINT school_settings_event_reminder_check CHECK (event_reminder_minutes >= 0);

COMMENT ON TABLE public.school_settings IS 'Singleton school-wide configuration used by the Rahma Edu Hub admin portal.';
